/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Aneeqah1;
import javax.swing.JOptionPane;

public class App {

   
    public static void main(String[] args) {
        int CreditDays = 30;
        JOptionPane.showMessageDialog(null,""+ CreditDays);
        JOptionPane.showMessageDialog(null,"Every bill is due in" + CreditDays + "days");
        
    }
}
